package com.neo.drools.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CheckGit implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CheckGit() {
	System.err.println("HEAD Commit");
		System.err.println("Pointed to local commit");
		System.err.println("Ensure that this is doen");
		System.err.println("One more check");
	}




}