package com.neo.drools.entity;



/**

 * This class was automatically generated by the data modeler tool.

 */



public class CheckGit implements java.io.Serializable {



    static final long serialVersionUID = 1L;



    public CheckGit() {

	System.err.println("HEAD Commit");

		System.err.println("Pointed to local commit");

		System.err.println("Ensure that this is doen");

		System.err.println("One more check");

		System.err.println("two more check");

		System.out.println("four more check");

		System.out.println("Five time check");

		System.out.println("Seven time check");

		System.out.println("Eighth Time Check time check");
		
System.out.println("Just Git Check");
System.err.println("cross check one more time to make sure it is working as expected");
System.err.println("Post-commit hook");
		
	}









}